
included: # paths to include during linting. `--path` is ignored if present.
  - Sources

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - DerivedData

disabled_rules:
  - closure_end_indentation
  - colon
  - no_extension_access_modifier
  - opening_brace
  - redundant_string_enum_value
  - sorted_imports
  - unneeded_parentheses_in_closure_argument
  - explicit_top_level_acl

opt_in_rules: # some rules are only opt-in
  - empty_count
  - force_cast
  - conditional_returns_on_newline
  - force_unwrapping
  - private_outlet
  - trailing_whitespace
  - closure_spacing
  - explicit_init
  - redundant_nil_coalescing
  - nimble_operator
  - overridden_super_call
  - file_header
  - number_separator
  - attributes
  - operator_usage_whitespace
  - prohibited_super_call
  - switch_case_on_newline
  - first_where
  - object_literal
  - explicit_type_interface
  - fatal_error_message
  - large_tuple
  - extension_access_modifier
  - implicit_return
  - array_init
  - contains_over_first_not_nil
  - explicit_enum_raw_value
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - pattern_matching_keywords
  - quick_discouraged_call
  - single_test_class
  - strict_fileprivate
  - trailing_closure
  - vertical_parameter_alignment_on_call
  - vertical_parameter_alignment
  - no_grouping_extension
  - implicitly_unwrapped_optional

force_cast: warning # implicitly

force_try:
  severity: warning

private_outlet:
  allow_private_set: true

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

identifier_name:
  min_length: # only min_length
    error: 3 # only error

file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  TesonetServersList
                    \/\/
                    \/\/  Created by .*? on \d{1,2}\/\d{1,2}\/\d{2}\.
                    \/\/  Copyright © \d{4} Tesonet\. All rights reserved\.
                    \/\/

colon:
  apply_to_dictionaries: false
